name: Pull requests Review

on:
  pull_request:
    types: [opened, reopened]
    branches: [master]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  pr-review:
    runs-on: ubuntu-latest

    steps:
    - name: PRMate Review
      uses: leewr9/prmate@v1
      with:
        pr-number: ${{ github.event.pull_request.number }}
        openai-api-key: ${{ secrets.OPENAI_API_KEY }}
        review-strict: 'True'
